# Generated by Django 5.1.5 on 2025-01-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail пользователя')),
                ('feedback_text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время написания отзыва')),
            ],
        ),
    ]
